#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpFKPTelyakov
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="telyakovKP")]
	public partial class dcAdresAbitDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertAdres_Abityrients(Adres_Abityrients instance);
    partial void UpdateAdres_Abityrients(Adres_Abityrients instance);
    partial void DeleteAdres_Abityrients(Adres_Abityrients instance);
    #endregion
		
		public dcAdresAbitDataContext() : 
				base(global::WpFKPTelyakov.Properties.Settings.Default.db, mappingSource)
		{
			OnCreated();
		}
		
		public dcAdresAbitDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAdresAbitDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAdresAbitDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAdresAbitDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adres_Abityrients> Adres_Abityrients
		{
			get
			{
				return this.GetTable<Adres_Abityrients>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adres_Abityrients")]
	public partial class Adres_Abityrients : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_abityr_adres;
		
		private string _kod_LD;
		
		private string _StranaP;
		
		private string _RegionP;
		
		private string _RaionP;
		
		private string _GorodP;
		
		private string _YlitsaP;
		
		private string _DomP;
		
		private string _KvP;
		
		private string _IndexP;
		
		private string _StranaF;
		
		private string _RegionF;
		
		private string _RaionF;
		
		private string _GorodF;
		
		private string _YlitsaF;
		
		private string _DomF;
		
		private string _KvF;
		
		private string _IndexF;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_abityr_adresChanging(int value);
    partial void OnID_abityr_adresChanged();
    partial void Onkod_LDChanging(string value);
    partial void Onkod_LDChanged();
    partial void OnStranaPChanging(string value);
    partial void OnStranaPChanged();
    partial void OnRegionPChanging(string value);
    partial void OnRegionPChanged();
    partial void OnRaionPChanging(string value);
    partial void OnRaionPChanged();
    partial void OnGorodPChanging(string value);
    partial void OnGorodPChanged();
    partial void OnYlitsaPChanging(string value);
    partial void OnYlitsaPChanged();
    partial void OnDomPChanging(string value);
    partial void OnDomPChanged();
    partial void OnKvPChanging(string value);
    partial void OnKvPChanged();
    partial void OnIndexPChanging(string value);
    partial void OnIndexPChanged();
    partial void OnStranaFChanging(string value);
    partial void OnStranaFChanged();
    partial void OnRegionFChanging(string value);
    partial void OnRegionFChanged();
    partial void OnRaionFChanging(string value);
    partial void OnRaionFChanged();
    partial void OnGorodFChanging(string value);
    partial void OnGorodFChanged();
    partial void OnYlitsaFChanging(string value);
    partial void OnYlitsaFChanged();
    partial void OnDomFChanging(string value);
    partial void OnDomFChanged();
    partial void OnKvFChanging(string value);
    partial void OnKvFChanged();
    partial void OnIndexFChanging(string value);
    partial void OnIndexFChanged();
    #endregion
		
		public Adres_Abityrients()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID abityr adres]", Storage="_ID_abityr_adres", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_abityr_adres
		{
			get
			{
				return this._ID_abityr_adres;
			}
			set
			{
				if ((this._ID_abityr_adres != value))
				{
					this.OnID_abityr_adresChanging(value);
					this.SendPropertyChanging();
					this._ID_abityr_adres = value;
					this.SendPropertyChanged("ID_abityr_adres");
					this.OnID_abityr_adresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[kod LD]", Storage="_kod_LD", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kod_LD
		{
			get
			{
				return this._kod_LD;
			}
			set
			{
				if ((this._kod_LD != value))
				{
					this.Onkod_LDChanging(value);
					this.SendPropertyChanging();
					this._kod_LD = value;
					this.SendPropertyChanged("kod_LD");
					this.Onkod_LDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StranaP", DbType="NVarChar(255)")]
		public string StranaP
		{
			get
			{
				return this._StranaP;
			}
			set
			{
				if ((this._StranaP != value))
				{
					this.OnStranaPChanging(value);
					this.SendPropertyChanging();
					this._StranaP = value;
					this.SendPropertyChanged("StranaP");
					this.OnStranaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionP", DbType="NVarChar(255)")]
		public string RegionP
		{
			get
			{
				return this._RegionP;
			}
			set
			{
				if ((this._RegionP != value))
				{
					this.OnRegionPChanging(value);
					this.SendPropertyChanging();
					this._RegionP = value;
					this.SendPropertyChanged("RegionP");
					this.OnRegionPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaionP", DbType="NVarChar(255)")]
		public string RaionP
		{
			get
			{
				return this._RaionP;
			}
			set
			{
				if ((this._RaionP != value))
				{
					this.OnRaionPChanging(value);
					this.SendPropertyChanging();
					this._RaionP = value;
					this.SendPropertyChanged("RaionP");
					this.OnRaionPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorodP", DbType="NVarChar(255)")]
		public string GorodP
		{
			get
			{
				return this._GorodP;
			}
			set
			{
				if ((this._GorodP != value))
				{
					this.OnGorodPChanging(value);
					this.SendPropertyChanging();
					this._GorodP = value;
					this.SendPropertyChanged("GorodP");
					this.OnGorodPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YlitsaP", DbType="NVarChar(255)")]
		public string YlitsaP
		{
			get
			{
				return this._YlitsaP;
			}
			set
			{
				if ((this._YlitsaP != value))
				{
					this.OnYlitsaPChanging(value);
					this.SendPropertyChanging();
					this._YlitsaP = value;
					this.SendPropertyChanged("YlitsaP");
					this.OnYlitsaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomP", DbType="NVarChar(255)")]
		public string DomP
		{
			get
			{
				return this._DomP;
			}
			set
			{
				if ((this._DomP != value))
				{
					this.OnDomPChanging(value);
					this.SendPropertyChanging();
					this._DomP = value;
					this.SendPropertyChanged("DomP");
					this.OnDomPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KvP", DbType="NVarChar(255)")]
		public string KvP
		{
			get
			{
				return this._KvP;
			}
			set
			{
				if ((this._KvP != value))
				{
					this.OnKvPChanging(value);
					this.SendPropertyChanging();
					this._KvP = value;
					this.SendPropertyChanged("KvP");
					this.OnKvPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexP", DbType="NVarChar(255)")]
		public string IndexP
		{
			get
			{
				return this._IndexP;
			}
			set
			{
				if ((this._IndexP != value))
				{
					this.OnIndexPChanging(value);
					this.SendPropertyChanging();
					this._IndexP = value;
					this.SendPropertyChanged("IndexP");
					this.OnIndexPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StranaF", DbType="NVarChar(255)")]
		public string StranaF
		{
			get
			{
				return this._StranaF;
			}
			set
			{
				if ((this._StranaF != value))
				{
					this.OnStranaFChanging(value);
					this.SendPropertyChanging();
					this._StranaF = value;
					this.SendPropertyChanged("StranaF");
					this.OnStranaFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionF", DbType="NVarChar(255)")]
		public string RegionF
		{
			get
			{
				return this._RegionF;
			}
			set
			{
				if ((this._RegionF != value))
				{
					this.OnRegionFChanging(value);
					this.SendPropertyChanging();
					this._RegionF = value;
					this.SendPropertyChanged("RegionF");
					this.OnRegionFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaionF", DbType="NVarChar(255)")]
		public string RaionF
		{
			get
			{
				return this._RaionF;
			}
			set
			{
				if ((this._RaionF != value))
				{
					this.OnRaionFChanging(value);
					this.SendPropertyChanging();
					this._RaionF = value;
					this.SendPropertyChanged("RaionF");
					this.OnRaionFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorodF", DbType="NVarChar(255)")]
		public string GorodF
		{
			get
			{
				return this._GorodF;
			}
			set
			{
				if ((this._GorodF != value))
				{
					this.OnGorodFChanging(value);
					this.SendPropertyChanging();
					this._GorodF = value;
					this.SendPropertyChanged("GorodF");
					this.OnGorodFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YlitsaF", DbType="NVarChar(255)")]
		public string YlitsaF
		{
			get
			{
				return this._YlitsaF;
			}
			set
			{
				if ((this._YlitsaF != value))
				{
					this.OnYlitsaFChanging(value);
					this.SendPropertyChanging();
					this._YlitsaF = value;
					this.SendPropertyChanged("YlitsaF");
					this.OnYlitsaFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomF", DbType="NVarChar(255)")]
		public string DomF
		{
			get
			{
				return this._DomF;
			}
			set
			{
				if ((this._DomF != value))
				{
					this.OnDomFChanging(value);
					this.SendPropertyChanging();
					this._DomF = value;
					this.SendPropertyChanged("DomF");
					this.OnDomFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KvF", DbType="NVarChar(255)")]
		public string KvF
		{
			get
			{
				return this._KvF;
			}
			set
			{
				if ((this._KvF != value))
				{
					this.OnKvFChanging(value);
					this.SendPropertyChanging();
					this._KvF = value;
					this.SendPropertyChanged("KvF");
					this.OnKvFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexF", DbType="NVarChar(255)")]
		public string IndexF
		{
			get
			{
				return this._IndexF;
			}
			set
			{
				if ((this._IndexF != value))
				{
					this.OnIndexFChanging(value);
					this.SendPropertyChanging();
					this._IndexF = value;
					this.SendPropertyChanged("IndexF");
					this.OnIndexFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
