#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpFKPTelyakov
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="telyakovKP")]
	public partial class dcDocumLicnostDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertDocuments_abit(Documents_abit instance);
    partial void UpdateDocuments_abit(Documents_abit instance);
    partial void DeleteDocuments_abit(Documents_abit instance);
    #endregion
		
		public dcDocumLicnostDataContext() : 
				base(global::WpFKPTelyakov.Properties.Settings.Default.db, mappingSource)
		{
			OnCreated();
		}
		
		public dcDocumLicnostDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDocumLicnostDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDocumLicnostDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDocumLicnostDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Documents_abit> Documents_abit
		{
			get
			{
				return this.GetTable<Documents_abit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Documents_abit")]
	public partial class Documents_abit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_abitur;
		
		private string _Kod_LD;
		
		private string _Grazdanstvo;
		
		private string _Tip_docum;
		
		private string _Seriy_num;
		
		private System.Nullable<System.DateTime> _Data_vidach;
		
		private string _Kod_podraz;
		
		private string _Kem_vidan;
		
		private string _Mesto_rozden;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_abiturChanging(int value);
    partial void OnID_abiturChanged();
    partial void OnKod_LDChanging(string value);
    partial void OnKod_LDChanged();
    partial void OnGrazdanstvoChanging(string value);
    partial void OnGrazdanstvoChanged();
    partial void OnTip_documChanging(string value);
    partial void OnTip_documChanged();
    partial void OnSeriy_numChanging(string value);
    partial void OnSeriy_numChanged();
    partial void OnData_vidachChanging(System.Nullable<System.DateTime> value);
    partial void OnData_vidachChanged();
    partial void OnKod_podrazChanging(string value);
    partial void OnKod_podrazChanged();
    partial void OnKem_vidanChanging(string value);
    partial void OnKem_vidanChanged();
    partial void OnMesto_rozdenChanging(string value);
    partial void OnMesto_rozdenChanged();
    #endregion
		
		public Documents_abit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID abitur]", Storage="_ID_abitur", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_abitur
		{
			get
			{
				return this._ID_abitur;
			}
			set
			{
				if ((this._ID_abitur != value))
				{
					this.OnID_abiturChanging(value);
					this.SendPropertyChanging();
					this._ID_abitur = value;
					this.SendPropertyChanged("ID_abitur");
					this.OnID_abiturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kod LD]", Storage="_Kod_LD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Kod_LD
		{
			get
			{
				return this._Kod_LD;
			}
			set
			{
				if ((this._Kod_LD != value))
				{
					this.OnKod_LDChanging(value);
					this.SendPropertyChanging();
					this._Kod_LD = value;
					this.SendPropertyChanged("Kod_LD");
					this.OnKod_LDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grazdanstvo", DbType="NVarChar(255)")]
		public string Grazdanstvo
		{
			get
			{
				return this._Grazdanstvo;
			}
			set
			{
				if ((this._Grazdanstvo != value))
				{
					this.OnGrazdanstvoChanging(value);
					this.SendPropertyChanging();
					this._Grazdanstvo = value;
					this.SendPropertyChanged("Grazdanstvo");
					this.OnGrazdanstvoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tip docum]", Storage="_Tip_docum", DbType="NVarChar(255)")]
		public string Tip_docum
		{
			get
			{
				return this._Tip_docum;
			}
			set
			{
				if ((this._Tip_docum != value))
				{
					this.OnTip_documChanging(value);
					this.SendPropertyChanging();
					this._Tip_docum = value;
					this.SendPropertyChanged("Tip_docum");
					this.OnTip_documChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Seriy num]", Storage="_Seriy_num", DbType="NVarChar(255)")]
		public string Seriy_num
		{
			get
			{
				return this._Seriy_num;
			}
			set
			{
				if ((this._Seriy_num != value))
				{
					this.OnSeriy_numChanging(value);
					this.SendPropertyChanging();
					this._Seriy_num = value;
					this.SendPropertyChanged("Seriy_num");
					this.OnSeriy_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data vidach]", Storage="_Data_vidach", DbType="Date")]
		public System.Nullable<System.DateTime> Data_vidach
		{
			get
			{
				return this._Data_vidach;
			}
			set
			{
				if ((this._Data_vidach != value))
				{
					this.OnData_vidachChanging(value);
					this.SendPropertyChanging();
					this._Data_vidach = value;
					this.SendPropertyChanged("Data_vidach");
					this.OnData_vidachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kod podraz]", Storage="_Kod_podraz", DbType="NVarChar(255)")]
		public string Kod_podraz
		{
			get
			{
				return this._Kod_podraz;
			}
			set
			{
				if ((this._Kod_podraz != value))
				{
					this.OnKod_podrazChanging(value);
					this.SendPropertyChanging();
					this._Kod_podraz = value;
					this.SendPropertyChanged("Kod_podraz");
					this.OnKod_podrazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kem vidan]", Storage="_Kem_vidan", DbType="NVarChar(255)")]
		public string Kem_vidan
		{
			get
			{
				return this._Kem_vidan;
			}
			set
			{
				if ((this._Kem_vidan != value))
				{
					this.OnKem_vidanChanging(value);
					this.SendPropertyChanging();
					this._Kem_vidan = value;
					this.SendPropertyChanged("Kem_vidan");
					this.OnKem_vidanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mesto rozden]", Storage="_Mesto_rozden", DbType="NVarChar(255)")]
		public string Mesto_rozden
		{
			get
			{
				return this._Mesto_rozden;
			}
			set
			{
				if ((this._Mesto_rozden != value))
				{
					this.OnMesto_rozdenChanging(value);
					this.SendPropertyChanging();
					this._Mesto_rozden = value;
					this.SendPropertyChanged("Mesto_rozden");
					this.OnMesto_rozdenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
